feat: Flyway Migration - Create All Tables
HEI-CleanCodeProject/FoodGen-Back pull request #6
Opened 2024-01-29 11:44 UTC by Miaritiana

@Sanmandresy

2024-01-29 15:16 UTC, Sanmandresy requested changes

2024-01-29 15:16 UTC, Sanmandresy commented on src/main/resources/db/migration/V0_2__create_region_table.sql
> +create extension if not exists "uuid-ossp";
No need to repeat this here as it was already declared in the first migration script

2024-01-29 15:16 UTC, Sanmandresy commented on src/main/resources/db/migration/V0_3__create_recipe_table.sql
> +create extension if not exists "uuid-ossp";
Same

2024-01-29 15:16 UTC, Sanmandresy commented on src/main/resources/db/migration/V0_4__create_ingredient_table.sql
> +create extension if not exists "uuid-ossp";
.

2024-01-29 15:16 UTC, Sanmandresy commented on src/main/resources/db/migration/V0_5__create_allergy_table.sql
> +create extension if not exists "uuid-ossp";
.

2024-01-29 15:16 UTC, Sanmandresy commented on src/main/resources/db/migration/V0_6__create_recipe_ingredients_table.sql
> +create extension if not exists "uuid-ossp";
.

2024-01-29 15:16 UTC, Sanmandresy commented on src/main/resources/db/migration/V0_7__create_meal_table.sql
> +create extension if not exists "uuid-ossp";
.

2024-01-29 15:16 UTC, Sanmandresy commented on src/main/resources/db/migration/V0_7__create_meal_table.sql
> +CREATE TABLE IF NOT EXISTS "recipe_ingredients"(
why are you creating "recipe_ingredients" again ?

2024-01-29 17:15 UTC, Miaritiana commented on src/main/resources/db/migration/V0_7__create_meal_table.sql
> +CREATE TABLE IF NOT EXISTS "recipe_ingredients"(
Oh! Excuse me.

2024-01-30 04:53 UTC, Sanmandresy approved these changes

2024-01-30 04:53 UTC, merged